// ═══════════════════════════════════════════════════════════════════════════════
// Strata Estimator — SIF Preview Modal
// Paper-styled preview of the exported SIF file contents. Shows the
// structured data that would be in the .sif package: header, line items,
// financial summary, constraints, and audit metadata.
// ═══════════════════════════════════════════════════════════════════════════════

import { Fragment, useEffect } from 'react'
import { clsx } from 'clsx'
import {
    Building2,
    ClipboardList,
    DollarSign,
    Download,
    FileCode2,
    MapPin,
    Package,
    ShieldCheck,
    X,
} from 'lucide-react'
import { useDemo } from '../../context/DemoContext'

interface SifPreviewModalProps {
    isOpen: boolean
    projectName: string
    customerName: string
    totalAmount: string
    itemCount: number
    onClose: () => void
    onDownload: () => void
}

export default function SifPreviewModal({
    isOpen,
    projectName,
    customerName,
    totalAmount,
    itemCount,
    onClose,
    onDownload,
}: SifPreviewModalProps) {
    const { isDemoActive, isSidebarCollapsed } = useDemo()
    const sidebarExpanded = isDemoActive && !isSidebarCollapsed
    const offsetClass = sidebarExpanded ? 'lg:left-80' : ''

    useEffect(() => {
        if (!isOpen) return
        const handleKey = (e: KeyboardEvent) => {
            if (e.key === 'Escape') onClose()
        }
        document.addEventListener('keydown', handleKey)
        return () => document.removeEventListener('keydown', handleKey)
    }, [isOpen, onClose])

    if (!isOpen) return null

    const today = new Date().toLocaleDateString('en-US', {
        month: 'long', day: 'numeric', year: 'numeric',
    })

    return (
        <div
            className={clsx(
                'fixed inset-0 z-[100] flex items-center justify-center bg-zinc-950/70 backdrop-blur-sm animate-in fade-in duration-200 p-4',
                offsetClass
            )}
            onClick={onClose}
            role="dialog"
            aria-modal="true"
        >
            <div
                className="w-full max-w-2xl max-h-[85vh] bg-card dark:bg-zinc-900 rounded-2xl shadow-2xl border border-border overflow-hidden animate-in zoom-in-95 duration-300 flex flex-col"
                onClick={(e) => e.stopPropagation()}
            >
                {/* Header */}
                <div className="px-6 py-4 bg-muted/40 border-b border-border flex items-center justify-between shrink-0">
                    <div className="flex items-center gap-3">
                        <span className="shrink-0 w-10 h-10 rounded-xl bg-primary/10 text-foreground dark:text-primary flex items-center justify-center">
                            <FileCode2 className="w-5 h-5" />
                        </span>
                        <div>
                            <p className="text-sm font-bold text-foreground uppercase tracking-wider">
                                SIF File Preview
                            </p>
                            <p className="text-[10px] text-muted-foreground mt-0.5">
                                {projectName.replace(/\s+/g, '_')}.sif · {today}
                            </p>
                        </div>
                    </div>
                    <button
                        type="button"
                        onClick={onClose}
                        className="p-1.5 rounded-lg text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
                    >
                        <X className="w-4 h-4" />
                    </button>
                </div>

                {/* Body */}
                <div className="flex-1 overflow-y-auto p-6 space-y-5 scrollbar-minimal">

                    {/* SIF Header section */}
                    <div className="rounded-xl bg-primary/5 dark:bg-primary/10 border border-primary/20 px-4 py-4">
                        <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider leading-none">
                            SIF Header · v2.1
                        </p>
                        <div className="grid grid-cols-2 gap-3 mt-3 text-[11px]">
                            <div>
                                <span className="text-muted-foreground">Format</span>
                                <p className="font-bold text-foreground">Strata Interchange Format</p>
                            </div>
                            <div>
                                <span className="text-muted-foreground">Schema version</span>
                                <p className="font-bold text-foreground">2.1.0</p>
                            </div>
                            <div>
                                <span className="text-muted-foreground">Generated by</span>
                                <p className="font-bold text-foreground">Strata Estimator v8</p>
                            </div>
                            <div>
                                <span className="text-muted-foreground">Checksum</span>
                                <p className="font-mono font-bold text-foreground text-[10px]">sha256:a4f8…3c1d</p>
                            </div>
                        </div>
                    </div>

                    {/* Project section */}
                    <section className="space-y-2">
                        <p className="text-[11px] font-bold text-foreground uppercase tracking-wider flex items-center gap-1.5">
                            <Building2 className="w-3 h-3" />
                            Project
                        </p>
                        <dl className="space-y-1.5 px-1 text-[11px]">
                            <div className="flex justify-between">
                                <dt className="text-muted-foreground">Customer</dt>
                                <dd className="font-semibold text-foreground">{customerName}</dd>
                            </div>
                            <div className="flex justify-between">
                                <dt className="text-muted-foreground">Project</dt>
                                <dd className="font-semibold text-foreground">{projectName}</dd>
                            </div>
                            <div className="flex justify-between">
                                <dt className="text-muted-foreground">Location</dt>
                                <dd className="font-semibold text-foreground">Fort Worth, TX (Downtown)</dd>
                            </div>
                            <div className="flex justify-between">
                                <dt className="text-muted-foreground">Venue type</dt>
                                <dd className="font-semibold text-foreground">Hospital campus</dd>
                            </div>
                        </dl>
                    </section>

                    {/* Line items summary */}
                    <section className="space-y-2">
                        <p className="text-[11px] font-bold text-foreground uppercase tracking-wider flex items-center gap-1.5">
                            <Package className="w-3 h-3" />
                            Line items · {itemCount} total
                        </p>
                        <div className="rounded-lg bg-muted/20 border border-border overflow-hidden">
                            <table className="w-full text-[10px]">
                                <thead>
                                    <tr className="bg-muted/40 text-muted-foreground font-bold uppercase tracking-wider">
                                        <th className="text-left px-3 py-2">Category</th>
                                        <th className="text-right px-3 py-2">Items</th>
                                        <th className="text-right px-3 py-2">Hours</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-border">
                                    <tr><td className="px-3 py-1.5 text-foreground">Seating</td><td className="px-3 py-1.5 text-right tabular-nums">14</td><td className="px-3 py-1.5 text-right tabular-nums">58.34</td></tr>
                                    <tr><td className="px-3 py-1.5 text-foreground">Tables</td><td className="px-3 py-1.5 text-right tabular-nums">4</td><td className="px-3 py-1.5 text-right tabular-nums">19.75</td></tr>
                                    <tr><td className="px-3 py-1.5 text-foreground">Accessories</td><td className="px-3 py-1.5 text-right tabular-nums">3</td><td className="px-3 py-1.5 text-right tabular-nums">30.00</td></tr>
                                    <tr><td className="px-3 py-1.5 text-foreground">Custom</td><td className="px-3 py-1.5 text-right tabular-nums">1</td><td className="px-3 py-1.5 text-right tabular-nums">12.00</td></tr>
                                    <tr><td className="px-3 py-1.5 text-foreground">Overhead</td><td className="px-3 py-1.5 text-right tabular-nums">2</td><td className="px-3 py-1.5 text-right tabular-nums">64.95</td></tr>
                                    <tr className="font-bold bg-muted/30">
                                        <td className="px-3 py-2 text-foreground">Total</td>
                                        <td className="px-3 py-2 text-right tabular-nums">{itemCount}</td>
                                        <td className="px-3 py-2 text-right tabular-nums">185.04</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </section>

                    {/* Financial */}
                    <section className="space-y-2">
                        <p className="text-[11px] font-bold text-foreground uppercase tracking-wider flex items-center gap-1.5">
                            <DollarSign className="w-3 h-3" />
                            Financial summary
                        </p>
                        <dl className="space-y-1.5 px-1 text-[11px]">
                            <div className="flex justify-between">
                                <dt className="text-muted-foreground">Labor total (185.04 hrs × $57/hr)</dt>
                                <dd className="font-semibold text-foreground">$10,547.28</dd>
                            </div>
                            <div className="flex justify-between">
                                <dt className="text-muted-foreground">Delivery total (Section A-G)</dt>
                                <dd className="font-semibold text-foreground">$7,729</dd>
                            </div>
                            <div className="flex justify-between border-t border-border pt-1.5">
                                <dt className="font-bold text-foreground">Combined estimate</dt>
                                <dd className="font-black text-foreground">${totalAmount}</dd>
                            </div>
                        </dl>
                    </section>

                    {/* Constraints */}
                    <section className="space-y-2">
                        <p className="text-[11px] font-bold text-foreground uppercase tracking-wider flex items-center gap-1.5">
                            <MapPin className="w-3 h-3" />
                            Site constraints embedded
                        </p>
                        <div className="flex flex-wrap gap-1.5">
                            {['Hospital +$114', 'Downtown +$57', 'No dock +15%', '2nd floor +5%', '32 mi transport', '185 hrs crew'].map((c) => (
                                <span key={c} className="text-[9px] font-bold uppercase tracking-wider px-2 py-1 rounded-md bg-muted/40 text-muted-foreground border border-border">
                                    {c}
                                </span>
                            ))}
                        </div>
                    </section>

                    {/* Integrity */}
                    <section className="space-y-2">
                        <p className="text-[11px] font-bold text-foreground uppercase tracking-wider flex items-center gap-1.5">
                            <ShieldCheck className="w-3 h-3" />
                            Integrity metadata
                        </p>
                        <div className="flex flex-wrap gap-1.5">
                            {['Dual-engine merged', 'Scope limits checked', 'Designer verified', 'Audit trail complete', 'Signed by Strata'].map((c) => (
                                <span key={c} className="text-[9px] font-bold uppercase tracking-wider px-2 py-1 rounded-md bg-green-500/10 text-green-700 dark:text-green-400 border border-green-500/30">
                                    {c}
                                </span>
                            ))}
                        </div>
                    </section>

                    <p className="text-[10px] text-muted-foreground italic text-center">
                        This SIF file can be imported into any Strata-compatible system
                        or shared with stakeholders for offline review.
                    </p>
                </div>

                {/* Footer */}
                <div className="px-6 py-3 bg-muted/30 border-t border-border flex items-center justify-between shrink-0">
                    <p className="text-[9px] text-muted-foreground">
                        Generated by Strata Estimator · {today}
                    </p>
                    <div className="flex items-center gap-2">
                        <button
                            type="button"
                            onClick={onClose}
                            className="px-4 py-2 rounded-lg text-[10px] font-bold uppercase tracking-wider text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
                        >
                            Close
                        </button>
                        <button
                            type="button"
                            onClick={() => { onDownload(); onClose() }}
                            className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-[10px] font-bold uppercase tracking-wider bg-primary text-primary-foreground hover:opacity-90 transition-opacity"
                        >
                            <Download className="w-3 h-3" />
                            Download .sif
                        </button>
                    </div>
                </div>
            </div>
        </div>
    )
}
